name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Grant execute permission for gradlew
        run: chmod +x Rest/essai/gradlew
      - name: Build and test
        working-directory: Rest/essai
        run: |
          export SHELL=/bin/bash
          ./gradlew build
      - name: Build Docker image
        working-directory: Rest/essai
        run: docker build -t car-rent:latest .
